name: super_app
description: "Shell de la super app financiera: compone los módulos de dominio."
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../packages/core
  design_system:
    path: ../../packages/design_system

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
